# =============================================================================
# ANTIGRAVITY — terraform.tfvars
# Auto-generated by bootstrap.sh on Mon Apr 20 23:17:03 CEST 2026
# DO NOT COMMIT — contains secrets
# =============================================================================

# ── OCI Auth ──────────────────────────────────────────────────────────────────
tenancy_ocid     = "ocid1.tenancy.oc1..aaaaaaaab2opxx6mrmmikviqgfvfszer32pjqht53ybzlxruxtp2hth45poq"
user_ocid        = "ocid1.user.oc1..aaaaaaaabreadmm45ntreqcs27coj5bz5bmr24b3k3ohhg6xirm625lapqfa"
fingerprint      = "d9:6c:49:52:ed:0a:e7:d8:93:84:15:4f:bd:a2:48:bd"
private_key_path = "~/.oci/oci_api_key.pem"
region           = "eu-frankfurt-1"

# ── Compartment (root tenancy) ────────────────────────────────────────────────
compartment_ocid = "ocid1.tenancy.oc1..aaaaaaaab2opxx6mrmmikviqgfvfszer32pjqht53ybzlxruxtp2hth45poq"

# ── Project ───────────────────────────────────────────────────────────────────
project_name = "antigravity"
environment  = "production"

# ── Networking ────────────────────────────────────────────────────────────────
vcn_cidr            = "10.0.0.0/16"
public_subnet_cidr  = "10.0.1.0/24"
private_subnet_cidr = "10.0.2.0/24"
db_subnet_cidr      = "10.0.3.0/24"

# ── Auto-generated ────────────────────────────────────────────────────────────
my_ip          = "88.209.32.72"
ssh_public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN1ByLAEy1M4QmUGbTX0VWp7sQYdHromrnh8Wju7QVRK Ravindra@bt-nac-o190.nac.uni-bayreuth.de"

# ── Compute shapes (Always Free eligible) ─────────────────────────────────────
frontend_shape      = "VM.Standard.E2.1.Micro"
backend_shape       = "VM.Standard.E2.1.Micro"
instance_image_ocid = ""

# ── HeatWave MySQL ────────────────────────────────────────────────────────────
db_admin_username = "admin"
db_admin_password = "80lSDz%FaZlFpSQQ"
db_name           = "antigravity"
